[package]
name = "winit-ui"
version = "0.1.0"
edition = "2024"
description = "A UI crate built around winit and pixels"
license = "MIT"
categories = ["gui", "rendering"]
keywords = ["ui", "window", "graphics", ]
readme = "README.md"
documentation = "https://docs.rs/winit-ui"
repository = "https://github.com/LordAfterEight/winit-ui"

[dependencies]
pixels = "0.17.1"
winit = "0.30.13"
